{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import dash\n",
    "from dash import dcc\n",
    "from dash import dcc\n",
    "from dash import html\n",
    "import pandas as pd\n",
    "import plotly.express as px\n",
    "import plotly.graph_objects as go\n",
    "import folium\n",
    "import dash_mantine_components as dmc\n",
    "from dash import Dash, dash_table\n",
    "import dash_bootstrap_components as dbc\n",
    "from dash import Dash, Input, Output, callback, dash_table\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "css = 'https://codepen.io/chriddyp/pen/bWLwgP.css'\n",
    "app = Dash(__name__, external_stylesheets=[css])\n",
    "server = app.server"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "def serve_layout():\n",
    "    data=pd.read_excel(\"Ultima_Consulta.xlsx\")\n",
    "    data=data.drop(\"Unnamed: 0\",axis=1)\n",
    "    \n",
    "            \n",
    "    fig_semaforo_general = px.pie(data,names='Semaforo_General',title='Semáforo general 🚦',hole=.3,color='Semaforo_General',color_discrete_map={'Rojo':'red',\n",
    "                                 'Verde':'green',\n",
    "                                 'Amarillo':'yellow',\n",
    "                                 'No es posible calcular':'gray',\n",
    "                                 'Calculando..':'#C39BD3',\n",
    "                                 })\n",
    "    fig_semaforo_general.update_layout({\n",
    "    'plot_bgcolor': 'rgba(0, 0, 0, 0)',\n",
    "    'paper_bgcolor': 'rgba(0, 0, 0, 0)',\n",
    "    },font=dict(\n",
    "        family=\"Verdana, Sans-serif\",\n",
    "        size=13,\n",
    "        color=\"white\"\n",
    "    ),title_x=0.5)\n",
    "    \n",
    "    X = ['En transito a origen','En origen','En transito a destino','En destino']\n",
    "    Verde=[len(data[(data[\"Estatus\"]=='En tránsito a origen')&(data[\"Semaforo_General\"]=='Verde')]),len(data[(data[\"Estatus\"]=='En origen')&(data[\"Semaforo_General\"]=='Verde')]),len(data[(data[\"Estatus\"]=='En tránsito a destino')&(data[\"Semaforo_General\"]=='Verde')]),len(data[(data[\"Estatus\"]=='En destino')&(data[\"Semaforo_General\"]=='Verde')])]\n",
    "    Amarillo=[len(data[(data[\"Estatus\"]=='En tránsito a origen')&(data[\"Semaforo_General\"]=='Amarillo')]),len(data[(data[\"Estatus\"]=='En origen')&(data[\"Semaforo_General\"]=='Amarillo')]),len(data[(data[\"Estatus\"]=='En tránsito a destino')&(data[\"Semaforo_General\"]=='Amarillo')]),len(data[(data[\"Estatus\"]=='En destino')&(data[\"Semaforo_General\"]=='Amarillo')])]\n",
    "    Rojo=[len(data[(data[\"Estatus\"]=='En tránsito a origen')&(data[\"Semaforo_General\"]=='Rojo')]),len(data[(data[\"Estatus\"]=='En origen')&(data[\"Semaforo_General\"]=='Rojo')]),len(data[(data[\"Estatus\"]=='En tránsito a destino')&(data[\"Semaforo_General\"]=='Rojo')]),len(data[(data[\"Estatus\"]=='En destino')&(data[\"Semaforo_General\"]=='Rojo')])]\n",
    "\n",
    "\n",
    "    fig_semaforo_estatus = go.Figure(data=[\n",
    "        go.Bar(name='En tiempo', x=X, y=Verde,text=Verde,marker_color=[\"green\"]*4),\n",
    "        go.Bar(name='En riesgo', x=X, y=Amarillo,text=Amarillo,marker_color=[\"yellow\"]*4),\n",
    "        go.Bar(name='Urgente', x=X, y=Rojo,text=Rojo,marker_color=[\"red\"]*4)\n",
    "    ])\n",
    "    # Change the bar mode\n",
    "    fig_semaforo_estatus.update_layout({\n",
    "    'plot_bgcolor': 'rgba(0, 0, 0, 0)',\n",
    "    'paper_bgcolor': 'rgba(0, 0, 0, 0)',\n",
    "    },barmode='stack',\n",
    "    font=dict(\n",
    "        family=\"Verdana, Sans-serif\",\n",
    "        size=13,\n",
    "        color=\"white\"\n",
    "    ),title='Semáforo por estatus 🚦',title_x=0.5)\n",
    "    \n",
    "\n",
    "\n",
    "    estatus_=pd.DataFrame(data.groupby(by=[\"Estatus\"]).size(),columns=[\"Count\"])\n",
    "    estatus_[\"Estatus\"]=estatus_.index\n",
    "    \n",
    "    fig_estatus = px.bar(estatus_,x='Estatus',y='Count',title='Estatus',color='Estatus',text_auto=True)\n",
    "    fig_estatus.update_layout({\n",
    "    'plot_bgcolor': 'rgba(0, 0, 0, 0)',\n",
    "    'paper_bgcolor': 'rgba(0, 0, 0, 0)',\n",
    "    },font=dict(\n",
    "        family=\"Verdana, Sans-serif\",\n",
    "        size=13,\n",
    "        color=\"white\"\n",
    "    ),title_x=0.5)\n",
    "\n",
    "    \n",
    "    colors={'Verde':'green','Rojo':'red','Amarillo':'yellow','Carga finalizada':'#C39BD3','No es posible calcular':'gray','Calculando..':'blue','Viaje finalizado':'orange'}\n",
    "    Puntos_I={}\n",
    "    for j in range(len(data)):\n",
    "        color=colors[data.loc[j,\"Semaforo_General\"]]\n",
    "        Puntos_I[data.loc[j,\"Folio\"]]=data.loc[j,\"Coordenadas\"].split(',')\n",
    "        Puntos_I[data.loc[j,\"Folio\"]].append(color)\n",
    "    \n",
    "    # crear un mapa base centrado en México\n",
    "    mapObj = folium.Map(location = [22.227205095658114, -100.3189399012432], zoom_start = 5)\n",
    "    # crear objeto marcador para cada camion, uno por uno para cada coordenada en los datos DataFrame\n",
    "    for i in Puntos_I:\n",
    "        # crear un marcador para el lugar\n",
    "        markerObj = folium.Marker(location = [Puntos_I[i][0],Puntos_I[i][1]], popup = i, tooltip= i,icon=folium.Icon(color=Puntos_I[i][2]))\n",
    "        # añadir marcador al mapa\n",
    "        markerObj.add_to(mapObj)\n",
    "    \n",
    "    markerObj.save('mapa.html')\n",
    "    \n",
    "\n",
    "    \n",
    "    return html.Div(style={'backgroundColor': '#111111'},\n",
    "    children=[\n",
    "        html.H1(children=\"KLS LOGISTICS\",className=\"hello\",\n",
    "    style={\"fontSize\": \"48px\",'color':'#dd191b','text-align':'center','fontWeight': 'bold'\n",
    "          }),\n",
    "        html.P(\n",
    "            children=\"Monitoreo Viajes Prisma🧊\",style={\"fontSize\": \"25px\",'color':'#ec8c88','text-align':'center'\n",
    "          }\n",
    "        ),\n",
    "        html.Iframe(srcDoc=open('mapa.html','r').read(),width='100%',height='600'),\n",
    "        dash_table.DataTable(data.loc[:,['Folio','Coordenadas','Estatus','Subestatus','Semaforo_General']].to_dict('records'), [{\"name\": i, \"id\": i} for i in data.loc[:,['Folio','Coordenadas',\"Estatus\",\"Subestatus\",'Semaforo_General']].columns],style_as_list_view=False,\n",
    "            style_cell={'padding': '2px','textAlign': 'center'},\n",
    "                                 style_data={'color': 'black',\n",
    "            'backgroundColor': '#adadad','whiteSpace': 'normal',\n",
    "            'height': 'auto'},\n",
    "            style_header={\n",
    "                'backgroundColor': '#721717',\n",
    "                'color':'white',\n",
    "            },style_data_conditional=[\n",
    "               {\n",
    "            \"if\": {\n",
    "                'column_id': 'Semaforo_General',\n",
    "                'filter_query': '{Semaforo_General} eq \"Rojo\"'\n",
    "            },\n",
    "            \"backgroundColor\": \"#FF0000\",\n",
    "            \"color\": \"white\"\n",
    "            },{\n",
    "            \"if\": {\n",
    "                'column_id': 'Semaforo_General',\n",
    "                'filter_query': '{Semaforo_General} eq \"Verde\"'\n",
    "            },\n",
    "            \"backgroundColor\": \"#00E572\",\n",
    "            \"color\": \"black\"\n",
    "            },\n",
    "            {\n",
    "            \"if\": {\n",
    "                'column_id': 'Semaforo_General',\n",
    "                'filter_query': '{Semaforo_General} eq \"Amarillo\"'\n",
    "            },\n",
    "            \"backgroundColor\": \"#FFFB00\",\n",
    "            \"color\": \"black\"\n",
    "            }\n",
    "            ],),\n",
    "        dcc.Graph(\n",
    "            figure=fig_semaforo_general,\n",
    "            style={'text-align':'center','width': '95vh', 'height': '95vh','display': 'inline-block'},\n",
    "            \n",
    "        ),\n",
    "        dcc.Graph(\n",
    "            figure=fig_semaforo_estatus,\n",
    "            style={'text-align':'center','width': '95vh', 'height': '95vh','display': 'inline-block'},\n",
    "            \n",
    "        ),\n",
    "\n",
    "\n",
    "        dcc.Graph(\n",
    "            figure=fig_estatus,\n",
    "            style={'text-align':'center','width': '200vh', 'height': '95vh'},\n",
    "        ),\n",
    "        \n",
    "        \n",
    "        \n",
    "    ],\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "app.layout=serve_layout"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      " * Serving Flask app '__main__'\n",
      " * Debug mode: on\n"
     ]
    }
   ],
   "source": [
    "if __name__ == '__main__':\n",
    "    app.run_server(debug=True,use_reloader=False)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.0"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "a6e122e8a42a6ce92ea3b6f23d6aba17237f63f40ce5a22bd494f5d18974f403"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
