{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import dash\n",
    "from dash import dcc\n",
    "from dash import dcc\n",
    "from dash import html\n",
    "import pandas as pd\n",
    "import plotly.express as px\n",
    "import plotly.graph_objects as go\n",
    "import folium\n",
    "import dash_mantine_components as dmc\n",
    "from dash import Dash, dash_table\n",
    "import dash_bootstrap_components as dbc\n",
    "from dash import Dash, Input, Output, callback, dash_table\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "css = 'https://codepen.io/chriddyp/pen/bWLwgP.css'\n",
    "app = Dash(__name__, external_stylesheets=[css])\n",
    "server = app.server"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "data=pd.read_excel(\"Ultima_Consulta.xlsx\")\n",
    "data=data.drop(\"Unnamed: 0\",axis=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Folio</th>\n",
       "      <th>Fecha Consulta</th>\n",
       "      <th>Coordenadas</th>\n",
       "      <th>Velocidad</th>\n",
       "      <th>Estado Unidad</th>\n",
       "      <th>Exceso velocidad</th>\n",
       "      <th>Km-carga</th>\n",
       "      <th>Hr-carga</th>\n",
       "      <th>Eta Origen</th>\n",
       "      <th>Km-descarga</th>\n",
       "      <th>...</th>\n",
       "      <th>Semaforo_Origen</th>\n",
       "      <th>Semaforo_Destino</th>\n",
       "      <th>Mensaje</th>\n",
       "      <th>Contacto</th>\n",
       "      <th>Driver</th>\n",
       "      <th>Semaforo_General</th>\n",
       "      <th>Eta fijo</th>\n",
       "      <th>Inicio movimiento</th>\n",
       "      <th>Tiempo encendido</th>\n",
       "      <th>Alerta descanso</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>23040791-01</td>\n",
       "      <td>2023-04-17 13:54:15.459</td>\n",
       "      <td>18.908256,-96.998391</td>\n",
       "      <td>0</td>\n",
       "      <td>Unidad detenida</td>\n",
       "      <td>No</td>\n",
       "      <td>16.9</td>\n",
       "      <td>0.281667</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>543</td>\n",
       "      <td>...</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>NaN</td>\n",
       "      <td>&lt;selenium.webdriver.chrome.webdriver.WebDriver...</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>2023-04-18 09:04:00</td>\n",
       "      <td>No se puede establecer</td>\n",
       "      <td>0</td>\n",
       "      <td>No se tiene información</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>23040760-01</td>\n",
       "      <td>2023-04-17 13:53:10.643</td>\n",
       "      <td>18.908256,-96.998391</td>\n",
       "      <td>0</td>\n",
       "      <td>Unidad detenida</td>\n",
       "      <td>No</td>\n",
       "      <td>16.9</td>\n",
       "      <td>0.281667</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>543</td>\n",
       "      <td>...</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>NaN</td>\n",
       "      <td>&lt;selenium.webdriver.chrome.webdriver.WebDriver...</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>2023-04-17 16:14:00</td>\n",
       "      <td>No se puede establecer</td>\n",
       "      <td>0</td>\n",
       "      <td>No se tiene información</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>23040753-01</td>\n",
       "      <td>2023-04-17 13:52:32.751</td>\n",
       "      <td>16.40289,-92.74631</td>\n",
       "      <td>77</td>\n",
       "      <td>Unidad encendida</td>\n",
       "      <td>Si</td>\n",
       "      <td>637</td>\n",
       "      <td>10.616667</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>73.1</td>\n",
       "      <td>...</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>NaN</td>\n",
       "      <td>&lt;selenium.webdriver.chrome.webdriver.WebDriver...</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>2023-04-17 10:59:00</td>\n",
       "      <td>2023-04-17 13:52:32.751000</td>\n",
       "      <td>0</td>\n",
       "      <td>Faltan5.0 horas para tomar descanso</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>23040751-01</td>\n",
       "      <td>2023-04-17 13:51:45.898</td>\n",
       "      <td>18.00857,-94.58787</td>\n",
       "      <td>0</td>\n",
       "      <td>Unidad detenida</td>\n",
       "      <td>No</td>\n",
       "      <td>309</td>\n",
       "      <td>5.150000</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>252</td>\n",
       "      <td>...</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>NaN</td>\n",
       "      <td>&lt;selenium.webdriver.chrome.webdriver.WebDriver...</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>2023-04-17 10:37:00</td>\n",
       "      <td>No se puede establecer</td>\n",
       "      <td>0</td>\n",
       "      <td>No se tiene información</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>23040750-01</td>\n",
       "      <td>2023-04-17 13:51:00.215</td>\n",
       "      <td>18.00857,-94.58787</td>\n",
       "      <td>0</td>\n",
       "      <td>Unidad detenida</td>\n",
       "      <td>No</td>\n",
       "      <td>309</td>\n",
       "      <td>5.150000</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>252</td>\n",
       "      <td>...</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>NaN</td>\n",
       "      <td>&lt;selenium.webdriver.chrome.webdriver.WebDriver...</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>2023-04-17 10:28:00</td>\n",
       "      <td>No se puede establecer</td>\n",
       "      <td>0</td>\n",
       "      <td>No se tiene información</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>23040738-01</td>\n",
       "      <td>2023-04-17 13:48:35.436</td>\n",
       "      <td>25.63443,-100.76702</td>\n",
       "      <td>0</td>\n",
       "      <td>Unidad detenida</td>\n",
       "      <td>No</td>\n",
       "      <td>756</td>\n",
       "      <td>15.120000</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>78.8</td>\n",
       "      <td>...</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>NaN</td>\n",
       "      <td>&lt;selenium.webdriver.chrome.webdriver.WebDriver...</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>2023-04-16 17:06:00</td>\n",
       "      <td>No se puede establecer</td>\n",
       "      <td>0</td>\n",
       "      <td>No se tiene información</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>23040735-01</td>\n",
       "      <td>2023-04-17 13:48:00.701</td>\n",
       "      <td>14.9062,-92.32157</td>\n",
       "      <td>0</td>\n",
       "      <td>No es posible calcular</td>\n",
       "      <td>No es posible calcular</td>\n",
       "      <td>No es posible calcular</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>No es posible calcular</td>\n",
       "      <td>No es posible calcular</td>\n",
       "      <td>...</td>\n",
       "      <td>Sin información</td>\n",
       "      <td>Sin información</td>\n",
       "      <td>No se puede calcular acción</td>\n",
       "      <td>NaN</td>\n",
       "      <td>&lt;selenium.webdriver.chrome.webdriver.WebDriver...</td>\n",
       "      <td>No es posible calcular</td>\n",
       "      <td>No es posible calcular</td>\n",
       "      <td>No es posible calcular</td>\n",
       "      <td>No es posible calcular</td>\n",
       "      <td>No es posible calcular</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>23040732-01</td>\n",
       "      <td>2023-04-17 13:47:11.481</td>\n",
       "      <td>32.6077305,-115.4226925</td>\n",
       "      <td>0</td>\n",
       "      <td>Unidad detenida</td>\n",
       "      <td>No</td>\n",
       "      <td>2146</td>\n",
       "      <td>11.766667</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>8.4</td>\n",
       "      <td>...</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>NaN</td>\n",
       "      <td>&lt;selenium.webdriver.chrome.webdriver.WebDriver...</td>\n",
       "      <td>Calculando..</td>\n",
       "      <td>2023-04-17 09:21:00</td>\n",
       "      <td>No se puede establecer</td>\n",
       "      <td>0</td>\n",
       "      <td>No se tiene información</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>8 rows × 32 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "         Folio          Fecha Consulta              Coordenadas  Velocidad  \\\n",
       "0  23040791-01 2023-04-17 13:54:15.459     18.908256,-96.998391          0   \n",
       "1  23040760-01 2023-04-17 13:53:10.643     18.908256,-96.998391          0   \n",
       "2  23040753-01 2023-04-17 13:52:32.751       16.40289,-92.74631         77   \n",
       "3  23040751-01 2023-04-17 13:51:45.898       18.00857,-94.58787          0   \n",
       "4  23040750-01 2023-04-17 13:51:00.215       18.00857,-94.58787          0   \n",
       "5  23040738-01 2023-04-17 13:48:35.436      25.63443,-100.76702          0   \n",
       "6  23040735-01 2023-04-17 13:48:00.701        14.9062,-92.32157          0   \n",
       "7  23040732-01 2023-04-17 13:47:11.481  32.6077305,-115.4226925          0   \n",
       "\n",
       "            Estado Unidad        Exceso velocidad                Km-carga  \\\n",
       "0         Unidad detenida                      No                    16.9   \n",
       "1         Unidad detenida                      No                    16.9   \n",
       "2        Unidad encendida                      Si                     637   \n",
       "3         Unidad detenida                      No                     309   \n",
       "4         Unidad detenida                      No                     309   \n",
       "5         Unidad detenida                      No                     756   \n",
       "6  No es posible calcular  No es posible calcular  No es posible calcular   \n",
       "7         Unidad detenida                      No                    2146   \n",
       "\n",
       "    Hr-carga              Eta Origen             Km-descarga  ...  \\\n",
       "0   0.281667            Calculando..                     543  ...   \n",
       "1   0.281667            Calculando..                     543  ...   \n",
       "2  10.616667            Calculando..                    73.1  ...   \n",
       "3   5.150000            Calculando..                     252  ...   \n",
       "4   5.150000            Calculando..                     252  ...   \n",
       "5  15.120000            Calculando..                    78.8  ...   \n",
       "6   0.000000  No es posible calcular  No es posible calcular  ...   \n",
       "7  11.766667            Calculando..                     8.4  ...   \n",
       "\n",
       "   Semaforo_Origen Semaforo_Destino                      Mensaje Contacto  \\\n",
       "0     Calculando..     Calculando..                 Calculando..      NaN   \n",
       "1     Calculando..     Calculando..                 Calculando..      NaN   \n",
       "2     Calculando..     Calculando..                 Calculando..      NaN   \n",
       "3     Calculando..     Calculando..                 Calculando..      NaN   \n",
       "4     Calculando..     Calculando..                 Calculando..      NaN   \n",
       "5     Calculando..     Calculando..                 Calculando..      NaN   \n",
       "6  Sin información  Sin información  No se puede calcular acción      NaN   \n",
       "7     Calculando..     Calculando..                 Calculando..      NaN   \n",
       "\n",
       "                                              Driver        Semaforo_General  \\\n",
       "0  <selenium.webdriver.chrome.webdriver.WebDriver...            Calculando..   \n",
       "1  <selenium.webdriver.chrome.webdriver.WebDriver...            Calculando..   \n",
       "2  <selenium.webdriver.chrome.webdriver.WebDriver...            Calculando..   \n",
       "3  <selenium.webdriver.chrome.webdriver.WebDriver...            Calculando..   \n",
       "4  <selenium.webdriver.chrome.webdriver.WebDriver...            Calculando..   \n",
       "5  <selenium.webdriver.chrome.webdriver.WebDriver...            Calculando..   \n",
       "6  <selenium.webdriver.chrome.webdriver.WebDriver...  No es posible calcular   \n",
       "7  <selenium.webdriver.chrome.webdriver.WebDriver...            Calculando..   \n",
       "\n",
       "                 Eta fijo           Inicio movimiento        Tiempo encendido  \\\n",
       "0     2023-04-18 09:04:00      No se puede establecer                       0   \n",
       "1     2023-04-17 16:14:00      No se puede establecer                       0   \n",
       "2     2023-04-17 10:59:00  2023-04-17 13:52:32.751000                       0   \n",
       "3     2023-04-17 10:37:00      No se puede establecer                       0   \n",
       "4     2023-04-17 10:28:00      No se puede establecer                       0   \n",
       "5     2023-04-16 17:06:00      No se puede establecer                       0   \n",
       "6  No es posible calcular      No es posible calcular  No es posible calcular   \n",
       "7     2023-04-17 09:21:00      No se puede establecer                       0   \n",
       "\n",
       "                       Alerta descanso  \n",
       "0              No se tiene información  \n",
       "1              No se tiene información  \n",
       "2  Faltan5.0 horas para tomar descanso  \n",
       "3              No se tiene información  \n",
       "4              No se tiene información  \n",
       "5              No se tiene información  \n",
       "6               No es posible calcular  \n",
       "7              No se tiene información  \n",
       "\n",
       "[8 rows x 32 columns]"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "def serve_layout():\n",
    "    data=pd.read_excel(\"Ultima_Consulta.xlsx\")\n",
    "    data=data.drop(\"Unnamed: 0\",axis=1)\n",
    "    \n",
    "            \n",
    "    fig_semaforo_general = px.pie(data,names='Semaforo_General',title='Semáforo general 🚦',hole=.3,color='Semaforo_General',color_discrete_map={'Rojo':'red',\n",
    "                                 'Verde':'green',\n",
    "                                 'Amarillo':'yellow',\n",
    "                                 'No es posible calcular':'gray',\n",
    "                                 'Calculando..':'#C39BD3',\n",
    "                                 })\n",
    "    fig_semaforo_general.update_layout({\n",
    "    'plot_bgcolor': 'rgba(0, 0, 0, 0)',\n",
    "    'paper_bgcolor': 'rgba(0, 0, 0, 0)',\n",
    "    },font=dict(\n",
    "        family=\"Verdana, Sans-serif\",\n",
    "        size=13,\n",
    "        color=\"white\"\n",
    "    ),title_x=0.5)\n",
    "    \n",
    "    X = ['En transito a origen','En origen','En transito a destino','En destino']\n",
    "    Verde=[len(data[(data[\"Estatus\"]=='En tránsito a origen')&(data[\"Semaforo_General\"]=='Verde')]),len(data[(data[\"Estatus\"]=='En origen')&(data[\"Semaforo_General\"]=='Verde')]),len(data[(data[\"Estatus\"]=='En tránsito a destino')&(data[\"Semaforo_General\"]=='Verde')]),len(data[(data[\"Estatus\"]=='En destino')&(data[\"Semaforo_General\"]=='Verde')])]\n",
    "    Amarillo=[len(data[(data[\"Estatus\"]=='En tránsito a origen')&(data[\"Semaforo_General\"]=='Amarillo')]),len(data[(data[\"Estatus\"]=='En origen')&(data[\"Semaforo_General\"]=='Amarillo')]),len(data[(data[\"Estatus\"]=='En tránsito a destino')&(data[\"Semaforo_General\"]=='Amarillo')]),len(data[(data[\"Estatus\"]=='En destino')&(data[\"Semaforo_General\"]=='Amarillo')])]\n",
    "    Rojo=[len(data[(data[\"Estatus\"]=='En tránsito a origen')&(data[\"Semaforo_General\"]=='Rojo')]),len(data[(data[\"Estatus\"]=='En origen')&(data[\"Semaforo_General\"]=='Rojo')]),len(data[(data[\"Estatus\"]=='En tránsito a destino')&(data[\"Semaforo_General\"]=='Rojo')]),len(data[(data[\"Estatus\"]=='En destino')&(data[\"Semaforo_General\"]=='Rojo')])]\n",
    "\n",
    "\n",
    "    fig_semaforo_estatus = go.Figure(data=[\n",
    "        go.Bar(name='En tiempo', x=X, y=Verde,text=Verde,marker_color=[\"green\"]*4),\n",
    "        go.Bar(name='En riesgo', x=X, y=Amarillo,text=Amarillo,marker_color=[\"yellow\"]*4),\n",
    "        go.Bar(name='Urgente', x=X, y=Rojo,text=Rojo,marker_color=[\"red\"]*4)\n",
    "    ])\n",
    "    # Change the bar mode\n",
    "    fig_semaforo_estatus.update_layout({\n",
    "    'plot_bgcolor': 'rgba(0, 0, 0, 0)',\n",
    "    'paper_bgcolor': 'rgba(0, 0, 0, 0)',\n",
    "    },barmode='stack',\n",
    "    font=dict(\n",
    "        family=\"Verdana, Sans-serif\",\n",
    "        size=13,\n",
    "        color=\"white\"\n",
    "    ),title='Semáforo por estatus 🚦',title_x=0.5)\n",
    "    \n",
    "\n",
    "\n",
    "    estatus_=pd.DataFrame(data.groupby(by=[\"Estatus\"]).size(),columns=[\"Count\"])\n",
    "    estatus_[\"Estatus\"]=estatus_.index\n",
    "    \n",
    "    fig_estatus = px.bar(estatus_,x='Estatus',y='Count',title='Estatus',color='Estatus',text_auto=True)\n",
    "    fig_estatus.update_layout({\n",
    "    'plot_bgcolor': 'rgba(0, 0, 0, 0)',\n",
    "    'paper_bgcolor': 'rgba(0, 0, 0, 0)',\n",
    "    },font=dict(\n",
    "        family=\"Verdana, Sans-serif\",\n",
    "        size=13,\n",
    "        color=\"white\"\n",
    "    ),title_x=0.5)\n",
    "\n",
    "    \n",
    "    colors={'Verde':'green','Rojo':'red','Amarillo':'yellow','Carga finalizada':'#C39BD3','No es posible calcular':'gray','Calculando..':'blue','Viaje finalizado':'orange'}\n",
    "    Puntos_I={}\n",
    "    for j in range(len(data)):\n",
    "        color=colors[data.loc[j,\"Semaforo_General\"]]\n",
    "        Puntos_I[data.loc[j,\"Folio\"]]=data.loc[j,\"Coordenadas\"].split(',')\n",
    "        Puntos_I[data.loc[j,\"Folio\"]].append(color)\n",
    "    \n",
    "    # crear un mapa base centrado en México\n",
    "    mapObj = folium.Map(location = [22.227205095658114, -100.3189399012432], zoom_start = 5)\n",
    "    # crear objeto marcador para cada camion, uno por uno para cada coordenada en los datos DataFrame\n",
    "    for i in Puntos_I:\n",
    "        # crear un marcador para el lugar\n",
    "        markerObj = folium.Marker(location = [Puntos_I[i][0],Puntos_I[i][1]], popup = i, tooltip= i,icon=folium.Icon(color=Puntos_I[i][2]))\n",
    "        # añadir marcador al mapa\n",
    "        markerObj.add_to(mapObj)\n",
    "    \n",
    "    markerObj.save('mapa.html')\n",
    "    \n",
    "\n",
    "    \n",
    "    return html.Div(style={'backgroundColor': '#111111'},\n",
    "    children=[\n",
    "        html.H1(children=\"KLS LOGISTICS\",className=\"hello\",\n",
    "    style={\"fontSize\": \"48px\",'color':'#dd191b','text-align':'center','fontWeight': 'bold'\n",
    "          }),\n",
    "        html.P(\n",
    "            children=\"Monitoreo Viajes Prisma🧊\",style={\"fontSize\": \"25px\",'color':'#ec8c88','text-align':'center'\n",
    "          }\n",
    "        ),\n",
    "        html.Iframe(srcDoc=open('mapa.html','r').read(),width='100%',height='600'),\n",
    "        dash_table.DataTable(data.loc[:,['Folio','Coordenadas','Estatus','Subestatus','Semaforo_General']].to_dict('records'), [{\"name\": i, \"id\": i} for i in data.loc[:,['Folio','Coordenadas',\"Estatus\",\"Subestatus\",'Semaforo_General']].columns],style_as_list_view=False,\n",
    "            style_cell={'padding': '2px','textAlign': 'center'},\n",
    "                                 style_data={'color': 'black',\n",
    "            'backgroundColor': '#adadad','whiteSpace': 'normal',\n",
    "            'height': 'auto'},\n",
    "            style_header={\n",
    "                'backgroundColor': '#721717',\n",
    "                'color':'white',\n",
    "            },style_data_conditional=[\n",
    "               {\n",
    "            \"if\": {\n",
    "                'column_id': 'Semaforo_General',\n",
    "                'filter_query': '{Semaforo_General} eq \"Rojo\"'\n",
    "            },\n",
    "            \"backgroundColor\": \"#FF0000\",\n",
    "            \"color\": \"white\"\n",
    "            },{\n",
    "            \"if\": {\n",
    "                'column_id': 'Semaforo_General',\n",
    "                'filter_query': '{Semaforo_General} eq \"Verde\"'\n",
    "            },\n",
    "            \"backgroundColor\": \"#00E572\",\n",
    "            \"color\": \"black\"\n",
    "            },\n",
    "            {\n",
    "            \"if\": {\n",
    "                'column_id': 'Semaforo_General',\n",
    "                'filter_query': '{Semaforo_General} eq \"Amarillo\"'\n",
    "            },\n",
    "            \"backgroundColor\": \"#FFFB00\",\n",
    "            \"color\": \"black\"\n",
    "            }\n",
    "            ],),\n",
    "        dcc.Graph(\n",
    "            figure=fig_semaforo_general,\n",
    "            style={'text-align':'center','width': '95vh', 'height': '95vh','display': 'inline-block'},\n",
    "            \n",
    "        ),\n",
    "        dcc.Graph(\n",
    "            figure=fig_semaforo_estatus,\n",
    "            style={'text-align':'center','width': '95vh', 'height': '95vh','display': 'inline-block'},\n",
    "            \n",
    "        ),\n",
    "\n",
    "\n",
    "        dcc.Graph(\n",
    "            figure=fig_estatus,\n",
    "            style={'text-align':'center','width': '200vh', 'height': '95vh'},\n",
    "        ),\n",
    "        \n",
    "        \n",
    "        \n",
    "    ],\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "app.layout=serve_layout"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      " * Serving Flask app '__main__'\n",
      " * Debug mode: on\n"
     ]
    }
   ],
   "source": [
    "if __name__ == '__main__':\n",
    "    app.run_server(debug=True,use_reloader=False)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.0"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "a6e122e8a42a6ce92ea3b6f23d6aba17237f63f40ce5a22bd494f5d18974f403"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
